"use client";

import React, { Suspense, useRef } from "react";
import {
  OrbitControls,
  PerspectiveCamera,
  Stars,
  Trail,
  useGLTF,
} from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import * as THREE_NS from "three";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/
const RocketModel: React.FC<{ url: string }> = ({ url }) => {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-explicit-any
  const { nodes } = useGLTF(url) as any;
  const groupRef = useRef<THREE_NS.Group>(null);

  // Continuous spinning animation
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.z += delta * 0.3;
    }
  });

  return (
    <group
      ref={groupRef}
      rotation={[-Math.PI / 2, 0, 0]}
      position={[12, -3, 0]}
      scale={5}
    >
      <group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
        <mesh
          receiveShadow
          castShadow
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
          geometry={nodes.planet002?.geometry}
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
          material={nodes.planet002?.material}
        />
        <mesh
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
          geometry={nodes.planet003?.geometry}
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
          material={nodes.planet003?.material}
        />
      </group>
    </group>
  );
};

// Preload the model
useGLTF.preload("/scene.glb");

// Shooting Star Component with Trail
interface ShootingStarProps {
  offset?: number;
  startX?: number;
  startY?: number;
  startZ?: number;
}

const ShootingStar: React.FC<ShootingStarProps> = ({
  offset = 0,
  startX = 0,
  startY = 0,
  startZ = 0,
}) => {
  const ref = useRef<THREE_NS.Mesh>(null);

  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  useFrame((state) => {
    if (!ref.current) return;
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-assignment
    const elapsed = state.clock.getElapsedTime() + offset;
    const t = (elapsed * 0.15) % 4; // Slower: Loop every 4 seconds

    // Linear diagonal motion from top-left to bottom-right
    const progress = Math.min(t, 1); // Clamp to 0-1
    ref.current.position.set(
      startX - progress * 30, // Longer travel distance
      startY - progress * 25, // Longer travel distance
      startZ - progress * 15, // Longer travel distance
    );

    // Fade out when resetting
    if ("opacity" in ref.current.material) {
      (ref.current.material as THREE_NS.MeshBasicMaterial).opacity =
        t > 1 ? 0 : 1;
    }
  });

  return (
    <Trail
      width={3}
      length={8}
      color={new THREE_NS.Color(2, 1, 10)}
      attenuation={(t) => t * t}
    >
      <mesh ref={ref}>
        <sphereGeometry args={[0.2]} />
        <meshBasicMaterial color={[10, 1, 10]} toneMapped={false} transparent />
      </mesh>
    </Trail>
  );
};

// Multiple Shooting Stars
const ShootingStars: React.FC<{ count?: number }> = ({ count = 6 }) => {
  const stars = React.useMemo(() => {
    const validCount = count || 6;
    return Array.from({ length: validCount }, (_, i) => ({
      offset: i * 1.5, // More staggered start times
      startX: -25 + Math.random() * 30, // Much wider spread (-15 to +15)
      startY: 10 + Math.random() * 15, // Higher starting points (20 to 35)
      startZ: -20 + Math.random() * 40, // Much deeper spread (-20 to +20)
    }));
  }, [count]);

  return (
    <>
      {stars.map((star, i) => (
        <ShootingStar
          key={i}
          offset={star.offset}
          startX={star.startX}
          startY={star.startY}
          startZ={star.startZ}
        />
      ))}
    </>
  );
};

export const RocketScene: React.FC = () => {
  return (
    <Canvas
      dpr={[1.5, 2]}
      linear
      shadows
      camera={{ position: [0, 0, 16], fov: 75 }}
      gl={{
        antialias: true,
        toneMapping: THREE_NS.ACESFilmicToneMapping,
        toneMappingExposure: 1.2,
      }}
    >
      {/* Background color */}
      <color attach="background" args={["#272730"]} />

      {/* Fog for depth */}
      <fog attach="fog" args={["#272730", 16, 30]} />

      {/* Lighting */}
      <ambientLight intensity={0.75 * Math.PI} />

      {/* Spotlight highlighting the rocket */}
      <PerspectiveCamera makeDefault position={[0, 0, 20]} fov={75}>
        <spotLight
          castShadow
          intensity={2.25 * Math.PI}
          decay={0}
          angle={0.2}
          penumbra={1}
          position={[-25, 20, -15]}
          shadow-mapSize={[1024, 1024]}
          shadow-bias={-0.0001}
        />
      </PerspectiveCamera>

      {/* Camera controls - reduced auto-rotate speed */}
      <OrbitControls
        autoRotate
        autoRotateSpeed={0.1}
        enablePan={false}
        enableZoom={false}
        maxPolarAngle={Math.PI / 2}
        minPolarAngle={Math.PI / 2}
      />

      {/* 3D Model */}
      <Suspense
        fallback={
          <mesh position={[12, -3, 0]}>
            <sphereGeometry args={[2, 32, 32]} />
            <meshStandardMaterial color="#4444ff" wireframe />
          </mesh>
        }
      >
        <RocketModel url="/scene.glb" />
      </Suspense>

      {/* Stars background */}
      <Stars radius={500} depth={50} count={1000} factor={10} />

      {/* Shooting stars */}
      <ShootingStars count={6} />

      {/* Post-processing effects */}
      <Suspense fallback={null}>
        <EffectComposer>
          <Bloom mipmapBlur luminanceThreshold={1} intensity={1.5} />
        </EffectComposer>
      </Suspense>
    </Canvas>
  );
};
