/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as calendar_attendance_mutations from "../calendar/attendance/mutations.js";
import type * as calendar_attendance_queries from "../calendar/attendance/queries.js";
import type * as calendar_attendees_mutations from "../calendar/attendees/mutations.js";
import type * as calendar_events_crud from "../calendar/events/crud.js";
import type * as calendar_events_orders from "../calendar/events/orders.js";
import type * as calendar_events_queries from "../calendar/events/queries.js";
import type * as calendar_invitations_mutations from "../calendar/invitations/mutations.js";
import type * as calendar_invitations_queries from "../calendar/invitations/queries.js";
import type * as calendar_lib_authUtils from "../calendar/lib/authUtils.js";
import type * as calendar_lib_dateUtils from "../calendar/lib/dateUtils.js";
import type * as calendar_permissions_mutations from "../calendar/permissions/mutations.js";
import type * as calendar_permissions_queries from "../calendar/permissions/queries.js";
import type * as calendar_queries from "../calendar/queries.js";
import type * as core_accessControl_helpers from "../core/accessControl/helpers.js";
import type * as core_accessControl_mutations from "../core/accessControl/mutations.js";
import type * as core_accessControl_queries from "../core/accessControl/queries.js";
import type * as core_accessControl_types from "../core/accessControl/types.js";
import type * as core_categories_mutations from "../core/categories/mutations.js";
import type * as core_categories_queries from "../core/categories/queries.js";
import type * as core_lib_auth from "../core/lib/auth.js";
import type * as core_lib_index from "../core/lib/index.js";
import type * as core_lib_permissions from "../core/lib/permissions.js";
import type * as core_media_categories from "../core/media/categories.js";
import type * as core_media_http from "../core/media/http.js";
import type * as core_media_integration from "../core/media/integration.js";
import type * as core_media_mutations from "../core/media/mutations.js";
import type * as core_media_queries from "../core/media/queries.js";
import type * as core_menus_mutations from "../core/menus/mutations.js";
import type * as core_menus_queries from "../core/menus/queries.js";
import type * as core_options from "../core/options.js";
import type * as core_organizations_helpers from "../core/organizations/helpers.js";
import type * as core_organizations_mutations from "../core/organizations/mutations.js";
import type * as core_organizations_queries from "../core/organizations/queries.js";
import type * as core_organizations_seed from "../core/organizations/seed.js";
import type * as core_organizations_types from "../core/organizations/types.js";
import type * as core_permissions_mutations from "../core/permissions/mutations.js";
import type * as core_permissions_queries from "../core/permissions/queries.js";
import type * as core_postTypes_lib_contentTypes from "../core/postTypes/lib/contentTypes.js";
import type * as core_postTypes_mutations from "../core/postTypes/mutations.js";
import type * as core_postTypes_queries from "../core/postTypes/queries.js";
import type * as core_postTypes_types from "../core/postTypes/types.js";
import type * as core_posts_mutations from "../core/posts/mutations.js";
import type * as core_posts_queries from "../core/posts/queries.js";
import type * as core_tags_mutations from "../core/tags/mutations.js";
import type * as core_tags_queries from "../core/tags/queries.js";
import type * as core_taxonomies_mutations from "../core/taxonomies/mutations.js";
import type * as core_taxonomies_queries from "../core/taxonomies/queries.js";
import type * as ecommerce_balances_mutations from "../ecommerce/balances/mutations.js";
import type * as ecommerce_balances_queries from "../ecommerce/balances/queries.js";
import type * as ecommerce_cart_cartUtils from "../ecommerce/cart/cartUtils.js";
import type * as ecommerce_cart_mutations from "../ecommerce/cart/mutations.js";
import type * as ecommerce_cart_queries from "../ecommerce/cart/queries.js";
import type * as ecommerce_categories_helpers from "../ecommerce/categories/helpers.js";
import type * as ecommerce_categories_mutations from "../ecommerce/categories/mutations.js";
import type * as ecommerce_categories_queries from "../ecommerce/categories/queries.js";
import type * as ecommerce_chargebacks_evidence from "../ecommerce/chargebacks/evidence.js";
import type * as ecommerce_chargebacks_mockData from "../ecommerce/chargebacks/mockData.js";
import type * as ecommerce_chargebacks_mutations from "../ecommerce/chargebacks/mutations.js";
import type * as ecommerce_chargebacks_queries from "../ecommerce/chargebacks/queries.js";
import type * as ecommerce_checkout_mutations from "../ecommerce/checkout/mutations.js";
import type * as ecommerce_checkout_queries from "../ecommerce/checkout/queries.js";
import type * as ecommerce_checkouts_mutations from "../ecommerce/checkouts/mutations.js";
import type * as ecommerce_checkouts_queries from "../ecommerce/checkouts/queries.js";
import type * as ecommerce_funnels_mutations from "../ecommerce/funnels/mutations.js";
import type * as ecommerce_funnels_queries from "../ecommerce/funnels/queries.js";
import type * as ecommerce_lib_index from "../ecommerce/lib/index.js";
import type * as ecommerce_lib_permissions from "../ecommerce/lib/permissions.js";
import type * as ecommerce_lib_pricing from "../ecommerce/lib/pricing.js";
import type * as ecommerce_lib_stockUtils from "../ecommerce/lib/stockUtils.js";
import type * as ecommerce_orders_mockData from "../ecommerce/orders/mockData.js";
import type * as ecommerce_orders_mutations from "../ecommerce/orders/mutations.js";
import type * as ecommerce_orders_notes from "../ecommerce/orders/notes.js";
import type * as ecommerce_orders_queries from "../ecommerce/orders/queries.js";
import type * as ecommerce_payments_mutations from "../ecommerce/payments/mutations.js";
import type * as ecommerce_payments_queries from "../ecommerce/payments/queries.js";
import type * as ecommerce_products_helpers from "../ecommerce/products/helpers.js";
import type * as ecommerce_products_media from "../ecommerce/products/media.js";
import type * as ecommerce_products_mutations from "../ecommerce/products/mutations.js";
import type * as ecommerce_products_queries from "../ecommerce/products/queries.js";
import type * as ecommerce_products_uploads from "../ecommerce/products/uploads.js";
import type * as ecommerce_transfers_mockData from "../ecommerce/transfers/mockData.js";
import type * as ecommerce_transfers_mutations from "../ecommerce/transfers/mutations.js";
import type * as ecommerce_transfers_queries from "../ecommerce/transfers/queries.js";
import type * as ecommerce_variations_mutations from "../ecommerce/variations/mutations.js";
import type * as ecommerce_variations_queries from "../ecommerce/variations/queries.js";
import type * as env from "../env.js";
import type * as http from "../http.js";
import type * as integrations_connections_cryptoActions from "../integrations/connections/cryptoActions.js";
import type * as integrations_connections_internalConnections from "../integrations/connections/internalConnections.js";
import type * as integrations_connections_mutations from "../integrations/connections/mutations.js";
import type * as integrations_connections_queries from "../integrations/connections/queries.js";
import type * as integrations_hardcodedSeeds from "../integrations/hardcodedSeeds.js";
import type * as integrations_importBasedSeeding from "../integrations/importBasedSeeding.js";
import type * as integrations_init from "../integrations/init.js";
import type * as integrations_integrationNodes_mutations from "../integrations/integrationNodes/mutations.js";
import type * as integrations_integrationNodes_queries from "../integrations/integrationNodes/queries.js";
import type * as integrations_integrationNodes_registry from "../integrations/integrationNodes/registry.js";
import type * as integrations_integrationNodes_seed from "../integrations/integrationNodes/seed.js";
import type * as integrations_lib_actionExecution from "../integrations/lib/actionExecution.js";
import type * as integrations_lib_crypto from "../integrations/lib/crypto.js";
import type * as integrations_lib_dryRun from "../integrations/lib/dryRun.js";
import type * as integrations_lib_errors from "../integrations/lib/errors.js";
import type * as integrations_lib_httpFetch from "../integrations/lib/httpFetch.js";
import type * as integrations_lib_idempotency from "../integrations/lib/idempotency.js";
import type * as integrations_lib_manifestDiscovery from "../integrations/lib/manifestDiscovery.js";
import type * as integrations_lib_manifestTypes from "../integrations/lib/manifestTypes.js";
import type * as integrations_lib_migrations from "../integrations/lib/migrations.js";
import type * as integrations_lib_registries from "../integrations/lib/registries.js";
import type * as integrations_lib_retry from "../integrations/lib/retry.js";
import type * as integrations_lib_runManagement from "../integrations/lib/runManagement.js";
import type * as integrations_lib_scenarioExecution from "../integrations/lib/scenarioExecution.js";
import type * as integrations_lib_seedingUtils from "../integrations/lib/seedingUtils.js";
import type * as integrations_manifestSeeding from "../integrations/manifestSeeding.js";
import type * as integrations_scenarios_mutations from "../integrations/scenarios/mutations.js";
import type * as integrations_scenarios_queries from "../integrations/scenarios/queries.js";
import type * as integrations_scenarios_reactFlowMutations from "../integrations/scenarios/reactFlowMutations.js";
import type * as integrations_scenarios_reactFlowQueries from "../integrations/scenarios/reactFlowQueries.js";
import type * as integrations_scenarios_scenarioLogs_mutations from "../integrations/scenarios/scenarioLogs/mutations.js";
import type * as integrations_scenarios_scenarioLogs_queries from "../integrations/scenarios/scenarioLogs/queries.js";
import type * as integrations_scenarios_scenarioNodes_mutations from "../integrations/scenarios/scenarioNodes/mutations.js";
import type * as integrations_scenarios_scenarioNodes_queries from "../integrations/scenarios/scenarioNodes/queries.js";
import type * as integrations_scenarios_scenarioRuns_mutations from "../integrations/scenarios/scenarioRuns/mutations.js";
import type * as integrations_scenarios_scenarioRuns_queries from "../integrations/scenarios/scenarioRuns/queries.js";
import type * as integrations_triggers_orderEvents from "../integrations/triggers/orderEvents.js";
import type * as integrations_triggers_registry from "../integrations/triggers/registry.js";
import type * as integrations_webhooks_handler from "../integrations/webhooks/handler.js";
import type * as lib_db from "../lib/db.js";
import type * as lib_fileTypes from "../lib/fileTypes.js";
import type * as lib_permissions_hasPermission from "../lib/permissions/hasPermission.js";
import type * as lib_permissions_index from "../lib/permissions/index.js";
import type * as lib_permissions_requirePermission from "../lib/permissions/requirePermission.js";
import type * as lib_permissions_userAuth from "../lib/permissions/userAuth.js";
import type * as lib_queryAnalyzer from "../lib/queryAnalyzer.js";
import type * as lib_slugs from "../lib/slugs.js";
import type * as lms_contentAccess_mutations from "../lms/contentAccess/mutations.js";
import type * as lms_contentAccess_queries from "../lms/contentAccess/queries.js";
import type * as lms_courses_queries from "../lms/courses/queries.js";
import type * as lms_lessons_helpers from "../lms/lessons/helpers.js";
import type * as lms_lessons_mutations from "../lms/lessons/mutations.js";
import type * as lms_lessons_queries from "../lms/lessons/queries.js";
import type * as lms_progress_helpers from "../lms/progress/helpers.js";
import type * as lms_progress_mutations from "../lms/progress/mutations.js";
import type * as lms_progress_queries from "../lms/progress/queries.js";
import type * as lms_quizzes_helpers from "../lms/quizzes/helpers.js";
import type * as lms_quizzes_mutations from "../lms/quizzes/mutations.js";
import type * as lms_quizzes_queries from "../lms/quizzes/queries.js";
import type * as lms_topics_helpers from "../lms/topics/helpers.js";
import type * as lms_topics_mutations from "../lms/topics/mutations.js";
import type * as lms_topics_queries from "../lms/topics/queries.js";
import type * as media_queries from "../media/queries.js";
import type * as notifications_helpers from "../notifications/helpers.js";
import type * as notifications_lib_feedNotifications from "../notifications/lib/feedNotifications.js";
import type * as notifications_lib_formatters from "../notifications/lib/formatters.js";
import type * as notifications_lib_index from "../notifications/lib/index.js";
import type * as notifications_lib_preferences from "../notifications/lib/preferences.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_preferences from "../notifications/preferences.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as notifications_types from "../notifications/types.js";
import type * as shared_auth from "../shared/auth.js";
import type * as shared_constants from "../shared/constants.js";
import type * as shared_dates from "../shared/dates.js";
import type * as shared_errors from "../shared/errors.js";
import type * as shared_formatting from "../shared/formatting.js";
import type * as shared_index from "../shared/index.js";
import type * as shared_pagination from "../shared/pagination.js";
import type * as shared_search from "../shared/search.js";
import type * as shared_validation from "../shared/validation.js";
import type * as shared_validators from "../shared/validators.js";
import type * as socialfeed_crons from "../socialfeed/crons.js";
import type * as socialfeed_lib_recommendationEngine from "../socialfeed/lib/recommendationEngine.js";
import type * as socialfeed_lib_trendingAlgorithm from "../socialfeed/lib/trendingAlgorithm.js";
import type * as socialfeed_mutations from "../socialfeed/mutations.js";
import type * as socialfeed_queries from "../socialfeed/queries.js";
import type * as tasks_boards_mutations from "../tasks/boards/mutations.js";
import type * as tasks_boards_queries from "../tasks/boards/queries.js";
import type * as tasks_mutations from "../tasks/mutations.js";
import type * as tasks_queries from "../tasks/queries.js";
import type * as users_helpers from "../users/helpers.js";
import type * as users_marketingTags_index from "../users/marketingTags/index.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as users_types from "../users/types.js";
import type * as vimeo_actions from "../vimeo/actions.js";
import type * as vimeo_crons from "../vimeo/crons.js";
import type * as vimeo_mutations from "../vimeo/mutations.js";
import type * as vimeo_queries from "../vimeo/queries.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "calendar/attendance/mutations": typeof calendar_attendance_mutations;
  "calendar/attendance/queries": typeof calendar_attendance_queries;
  "calendar/attendees/mutations": typeof calendar_attendees_mutations;
  "calendar/events/crud": typeof calendar_events_crud;
  "calendar/events/orders": typeof calendar_events_orders;
  "calendar/events/queries": typeof calendar_events_queries;
  "calendar/invitations/mutations": typeof calendar_invitations_mutations;
  "calendar/invitations/queries": typeof calendar_invitations_queries;
  "calendar/lib/authUtils": typeof calendar_lib_authUtils;
  "calendar/lib/dateUtils": typeof calendar_lib_dateUtils;
  "calendar/permissions/mutations": typeof calendar_permissions_mutations;
  "calendar/permissions/queries": typeof calendar_permissions_queries;
  "calendar/queries": typeof calendar_queries;
  "core/accessControl/helpers": typeof core_accessControl_helpers;
  "core/accessControl/mutations": typeof core_accessControl_mutations;
  "core/accessControl/queries": typeof core_accessControl_queries;
  "core/accessControl/types": typeof core_accessControl_types;
  "core/categories/mutations": typeof core_categories_mutations;
  "core/categories/queries": typeof core_categories_queries;
  "core/lib/auth": typeof core_lib_auth;
  "core/lib/index": typeof core_lib_index;
  "core/lib/permissions": typeof core_lib_permissions;
  "core/media/categories": typeof core_media_categories;
  "core/media/http": typeof core_media_http;
  "core/media/integration": typeof core_media_integration;
  "core/media/mutations": typeof core_media_mutations;
  "core/media/queries": typeof core_media_queries;
  "core/menus/mutations": typeof core_menus_mutations;
  "core/menus/queries": typeof core_menus_queries;
  "core/options": typeof core_options;
  "core/organizations/helpers": typeof core_organizations_helpers;
  "core/organizations/mutations": typeof core_organizations_mutations;
  "core/organizations/queries": typeof core_organizations_queries;
  "core/organizations/seed": typeof core_organizations_seed;
  "core/organizations/types": typeof core_organizations_types;
  "core/permissions/mutations": typeof core_permissions_mutations;
  "core/permissions/queries": typeof core_permissions_queries;
  "core/postTypes/lib/contentTypes": typeof core_postTypes_lib_contentTypes;
  "core/postTypes/mutations": typeof core_postTypes_mutations;
  "core/postTypes/queries": typeof core_postTypes_queries;
  "core/postTypes/types": typeof core_postTypes_types;
  "core/posts/mutations": typeof core_posts_mutations;
  "core/posts/queries": typeof core_posts_queries;
  "core/tags/mutations": typeof core_tags_mutations;
  "core/tags/queries": typeof core_tags_queries;
  "core/taxonomies/mutations": typeof core_taxonomies_mutations;
  "core/taxonomies/queries": typeof core_taxonomies_queries;
  "ecommerce/balances/mutations": typeof ecommerce_balances_mutations;
  "ecommerce/balances/queries": typeof ecommerce_balances_queries;
  "ecommerce/cart/cartUtils": typeof ecommerce_cart_cartUtils;
  "ecommerce/cart/mutations": typeof ecommerce_cart_mutations;
  "ecommerce/cart/queries": typeof ecommerce_cart_queries;
  "ecommerce/categories/helpers": typeof ecommerce_categories_helpers;
  "ecommerce/categories/mutations": typeof ecommerce_categories_mutations;
  "ecommerce/categories/queries": typeof ecommerce_categories_queries;
  "ecommerce/chargebacks/evidence": typeof ecommerce_chargebacks_evidence;
  "ecommerce/chargebacks/mockData": typeof ecommerce_chargebacks_mockData;
  "ecommerce/chargebacks/mutations": typeof ecommerce_chargebacks_mutations;
  "ecommerce/chargebacks/queries": typeof ecommerce_chargebacks_queries;
  "ecommerce/checkout/mutations": typeof ecommerce_checkout_mutations;
  "ecommerce/checkout/queries": typeof ecommerce_checkout_queries;
  "ecommerce/checkouts/mutations": typeof ecommerce_checkouts_mutations;
  "ecommerce/checkouts/queries": typeof ecommerce_checkouts_queries;
  "ecommerce/funnels/mutations": typeof ecommerce_funnels_mutations;
  "ecommerce/funnels/queries": typeof ecommerce_funnels_queries;
  "ecommerce/lib/index": typeof ecommerce_lib_index;
  "ecommerce/lib/permissions": typeof ecommerce_lib_permissions;
  "ecommerce/lib/pricing": typeof ecommerce_lib_pricing;
  "ecommerce/lib/stockUtils": typeof ecommerce_lib_stockUtils;
  "ecommerce/orders/mockData": typeof ecommerce_orders_mockData;
  "ecommerce/orders/mutations": typeof ecommerce_orders_mutations;
  "ecommerce/orders/notes": typeof ecommerce_orders_notes;
  "ecommerce/orders/queries": typeof ecommerce_orders_queries;
  "ecommerce/payments/mutations": typeof ecommerce_payments_mutations;
  "ecommerce/payments/queries": typeof ecommerce_payments_queries;
  "ecommerce/products/helpers": typeof ecommerce_products_helpers;
  "ecommerce/products/media": typeof ecommerce_products_media;
  "ecommerce/products/mutations": typeof ecommerce_products_mutations;
  "ecommerce/products/queries": typeof ecommerce_products_queries;
  "ecommerce/products/uploads": typeof ecommerce_products_uploads;
  "ecommerce/transfers/mockData": typeof ecommerce_transfers_mockData;
  "ecommerce/transfers/mutations": typeof ecommerce_transfers_mutations;
  "ecommerce/transfers/queries": typeof ecommerce_transfers_queries;
  "ecommerce/variations/mutations": typeof ecommerce_variations_mutations;
  "ecommerce/variations/queries": typeof ecommerce_variations_queries;
  env: typeof env;
  http: typeof http;
  "integrations/connections/cryptoActions": typeof integrations_connections_cryptoActions;
  "integrations/connections/internalConnections": typeof integrations_connections_internalConnections;
  "integrations/connections/mutations": typeof integrations_connections_mutations;
  "integrations/connections/queries": typeof integrations_connections_queries;
  "integrations/hardcodedSeeds": typeof integrations_hardcodedSeeds;
  "integrations/importBasedSeeding": typeof integrations_importBasedSeeding;
  "integrations/init": typeof integrations_init;
  "integrations/integrationNodes/mutations": typeof integrations_integrationNodes_mutations;
  "integrations/integrationNodes/queries": typeof integrations_integrationNodes_queries;
  "integrations/integrationNodes/registry": typeof integrations_integrationNodes_registry;
  "integrations/integrationNodes/seed": typeof integrations_integrationNodes_seed;
  "integrations/lib/actionExecution": typeof integrations_lib_actionExecution;
  "integrations/lib/crypto": typeof integrations_lib_crypto;
  "integrations/lib/dryRun": typeof integrations_lib_dryRun;
  "integrations/lib/errors": typeof integrations_lib_errors;
  "integrations/lib/httpFetch": typeof integrations_lib_httpFetch;
  "integrations/lib/idempotency": typeof integrations_lib_idempotency;
  "integrations/lib/manifestDiscovery": typeof integrations_lib_manifestDiscovery;
  "integrations/lib/manifestTypes": typeof integrations_lib_manifestTypes;
  "integrations/lib/migrations": typeof integrations_lib_migrations;
  "integrations/lib/registries": typeof integrations_lib_registries;
  "integrations/lib/retry": typeof integrations_lib_retry;
  "integrations/lib/runManagement": typeof integrations_lib_runManagement;
  "integrations/lib/scenarioExecution": typeof integrations_lib_scenarioExecution;
  "integrations/lib/seedingUtils": typeof integrations_lib_seedingUtils;
  "integrations/manifestSeeding": typeof integrations_manifestSeeding;
  "integrations/scenarios/mutations": typeof integrations_scenarios_mutations;
  "integrations/scenarios/queries": typeof integrations_scenarios_queries;
  "integrations/scenarios/reactFlowMutations": typeof integrations_scenarios_reactFlowMutations;
  "integrations/scenarios/reactFlowQueries": typeof integrations_scenarios_reactFlowQueries;
  "integrations/scenarios/scenarioLogs/mutations": typeof integrations_scenarios_scenarioLogs_mutations;
  "integrations/scenarios/scenarioLogs/queries": typeof integrations_scenarios_scenarioLogs_queries;
  "integrations/scenarios/scenarioNodes/mutations": typeof integrations_scenarios_scenarioNodes_mutations;
  "integrations/scenarios/scenarioNodes/queries": typeof integrations_scenarios_scenarioNodes_queries;
  "integrations/scenarios/scenarioRuns/mutations": typeof integrations_scenarios_scenarioRuns_mutations;
  "integrations/scenarios/scenarioRuns/queries": typeof integrations_scenarios_scenarioRuns_queries;
  "integrations/triggers/orderEvents": typeof integrations_triggers_orderEvents;
  "integrations/triggers/registry": typeof integrations_triggers_registry;
  "integrations/webhooks/handler": typeof integrations_webhooks_handler;
  "lib/db": typeof lib_db;
  "lib/fileTypes": typeof lib_fileTypes;
  "lib/permissions/hasPermission": typeof lib_permissions_hasPermission;
  "lib/permissions/index": typeof lib_permissions_index;
  "lib/permissions/requirePermission": typeof lib_permissions_requirePermission;
  "lib/permissions/userAuth": typeof lib_permissions_userAuth;
  "lib/queryAnalyzer": typeof lib_queryAnalyzer;
  "lib/slugs": typeof lib_slugs;
  "lms/contentAccess/mutations": typeof lms_contentAccess_mutations;
  "lms/contentAccess/queries": typeof lms_contentAccess_queries;
  "lms/courses/queries": typeof lms_courses_queries;
  "lms/lessons/helpers": typeof lms_lessons_helpers;
  "lms/lessons/mutations": typeof lms_lessons_mutations;
  "lms/lessons/queries": typeof lms_lessons_queries;
  "lms/progress/helpers": typeof lms_progress_helpers;
  "lms/progress/mutations": typeof lms_progress_mutations;
  "lms/progress/queries": typeof lms_progress_queries;
  "lms/quizzes/helpers": typeof lms_quizzes_helpers;
  "lms/quizzes/mutations": typeof lms_quizzes_mutations;
  "lms/quizzes/queries": typeof lms_quizzes_queries;
  "lms/topics/helpers": typeof lms_topics_helpers;
  "lms/topics/mutations": typeof lms_topics_mutations;
  "lms/topics/queries": typeof lms_topics_queries;
  "media/queries": typeof media_queries;
  "notifications/helpers": typeof notifications_helpers;
  "notifications/lib/feedNotifications": typeof notifications_lib_feedNotifications;
  "notifications/lib/formatters": typeof notifications_lib_formatters;
  "notifications/lib/index": typeof notifications_lib_index;
  "notifications/lib/preferences": typeof notifications_lib_preferences;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/preferences": typeof notifications_preferences;
  "notifications/queries": typeof notifications_queries;
  "notifications/types": typeof notifications_types;
  "shared/auth": typeof shared_auth;
  "shared/constants": typeof shared_constants;
  "shared/dates": typeof shared_dates;
  "shared/errors": typeof shared_errors;
  "shared/formatting": typeof shared_formatting;
  "shared/index": typeof shared_index;
  "shared/pagination": typeof shared_pagination;
  "shared/search": typeof shared_search;
  "shared/validation": typeof shared_validation;
  "shared/validators": typeof shared_validators;
  "socialfeed/crons": typeof socialfeed_crons;
  "socialfeed/lib/recommendationEngine": typeof socialfeed_lib_recommendationEngine;
  "socialfeed/lib/trendingAlgorithm": typeof socialfeed_lib_trendingAlgorithm;
  "socialfeed/mutations": typeof socialfeed_mutations;
  "socialfeed/queries": typeof socialfeed_queries;
  "tasks/boards/mutations": typeof tasks_boards_mutations;
  "tasks/boards/queries": typeof tasks_boards_queries;
  "tasks/mutations": typeof tasks_mutations;
  "tasks/queries": typeof tasks_queries;
  "users/helpers": typeof users_helpers;
  "users/marketingTags/index": typeof users_marketingTags_index;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "users/types": typeof users_types;
  "vimeo/actions": typeof vimeo_actions;
  "vimeo/crons": typeof vimeo_crons;
  "vimeo/mutations": typeof vimeo_mutations;
  "vimeo/queries": typeof vimeo_queries;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
