import type { PluginDefinition } from "./types";
import {
  CourseBuilderTab,
  CourseLinkedProductTab,
  CourseMembersTab,
} from "~/plugins/lms/course-tabs";
import { CommerceStorefrontSettings } from "~/plugins/settings/commerce-storefront-settings";
import { LmsSettingsPage } from "~/plugins/settings/lms-settings-page";

export const pluginDefinitions: PluginDefinition[] = [
  {
    id: "lms",
    name: "Learning Management System",
    description: "Courses, lessons, topics and quizzes with learner tracking.",
    longDescription:
      "Perfect for education businesses. Enabling this plugin provisions all LMS post types with archive pages, admin menus and rich metadata.",
    features: [
      "Course + lesson builders",
      "Topic + quiz post types",
      "Access control hooks",
      "Completion tracking",
    ],
    postTypes: [
      {
        name: "Courses",
        slug: "courses",
        description: "Top-level LMS course container.",
        isPublic: true,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          title: true,
          editor: true,
          excerpt: true,
          featuredImage: true,
          customFields: true,
          revisions: true,
          taxonomy: true,
        },
        rewrite: {
          hasArchive: true,
          archiveSlug: "courses",
          singleSlug: "course",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: true,
          label: "Courses",
          slug: "courses",
          parent: "lms",
          icon: "GraduationCap",
          position: 30,
        },
        singleView: {
          basePath: "/admin/lms/courses",
          defaultTab: "edit",
          tabs: [
            {
              id: "edit",
              slug: "edit",
              label: "Edit",
              description: "Update course metadata, hero imagery and SEO.",
              usesDefaultEditor: true,
            },
            {
              id: "builder",
              slug: "builder",
              label: "Builder",
              description: "Control the modular course outline.",
              render: (props) => <CourseBuilderTab {...props} />,
            },
            {
              id: "members",
              slug: "members",
              label: "Members",
              description: "Invite and manage enrolled learners.",
              render: (props) => <CourseMembersTab {...props} />,
            },
            {
              id: "linked-product",
              slug: "linked-product",
              label: "Linked Product",
              description: "Map this course to a storefront listing.",
              render: (props) => <CourseLinkedProductTab {...props} />,
            },
          ],
        },
      },
      {
        name: "Lessons",
        slug: "lessons",
        description: "Lessons nested under a course.",
        isPublic: true,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          title: true,
          editor: true,
          featuredImage: true,
          customFields: true,
          revisions: true,
        },
        rewrite: {
          hasArchive: false,
          singleSlug: "lesson",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: true,
          label: "Lessons",
          slug: "lessons",
          parent: "lms",
          icon: "BookOpenCheck",
          position: 31,
        },
      },
      {
        name: "Topics",
        slug: "topics",
        description: "Lesson topics / sub-lessons.",
        isPublic: false,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          title: true,
          editor: true,
          customFields: true,
        },
        rewrite: {
          hasArchive: false,
          singleSlug: "topic",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: true,
          label: "Topics",
          slug: "topics",
          parent: "lms",
          icon: "ListChecks",
          position: 32,
        },
      },
      {
        name: "Quizzes",
        slug: "quizzes",
        description: "Assessments that connect to lessons/topics.",
        isPublic: false,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          title: true,
          editor: true,
          postMeta: true,
        },
        rewrite: {
          hasArchive: false,
          singleSlug: "quiz",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: true,
          label: "Quizzes",
          slug: "quizzes",
          parent: "lms",
          icon: "ClipboardCheck",
          position: 33,
        },
      },
    ],
    settingsPages: [
      {
        id: "lms-settings",
        slug: "settings",
        label: "Settings",
        description: "Configure branding, learner defaults and assessments.",
        render: (props) => <LmsSettingsPage {...props} />,
      },
    ],
  },
  {
    id: "commerce",
    name: "Ecommerce",
    description: "Products, orders and catalog components.",
    longDescription:
      "Sell digital or physical products. Adds product + order post types with store specific settings.",
    features: [
      "Products, orders, coupons",
      "Inventory hooks",
      "Catalog API endpoints",
      "Admin store sidebar items",
    ],
    postTypes: [
      {
        name: "Products",
        slug: "products",
        description: "Shoppable catalog entries.",
        isPublic: true,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          title: true,
          editor: true,
          excerpt: true,
          featuredImage: true,
          customFields: true,
          postMeta: true,
          taxonomy: true,
        },
        rewrite: {
          hasArchive: true,
          archiveSlug: "store",
          singleSlug: "product",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: true,
          label: "Products",
          slug: "store/products",
          icon: "Package",
          position: 40,
        },
      },
      {
        name: "Orders",
        slug: "orders",
        description: "Order records stored as entries.",
        isPublic: false,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          title: true,
          customFields: true,
          postMeta: true,
        },
        rewrite: {
          hasArchive: false,
          singleSlug: "order",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: true,
          label: "Orders",
          slug: "store/orders",
          icon: "Receipt",
          position: 41,
        },
      },
    ],
    settingsPages: [
      {
        id: "commerce-storefront",
        slug: "storefront",
        label: "Storefront",
        description: "Currency, shipping and checkout defaults.",
        render: (props) => <CommerceStorefrontSettings {...props} />,
      },
    ],
  },
  {
    id: "helpdesk",
    name: "Helpdesk",
    description: "Tickets and threaded conversations.",
    longDescription:
      "Provide support for your customers. Adds ticket post types and sidebar entries.",
    features: [
      "Tickets + replies",
      "Priority + status fields",
      "Internal / external notes",
      "Admin navigation items",
    ],
    postTypes: [
      {
        name: "Tickets",
        slug: "tickets",
        description: "Primary helpdesk ticket entity.",
        isPublic: false,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          title: true,
          editor: true,
          customFields: true,
          postMeta: true,
        },
        rewrite: {
          hasArchive: false,
          singleSlug: "ticket",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: true,
          label: "Tickets",
          slug: "helpdesk/tickets",
          icon: "LifeBuoy",
          position: 50,
        },
      },
      {
        name: "Ticket Replies",
        slug: "ticket-replies",
        description: "Threaded responses linked to a ticket.",
        isPublic: false,
        includeTimestamps: true,
        enableApi: true,
        supports: {
          editor: true,
          customFields: true,
        },
        rewrite: {
          hasArchive: false,
          singleSlug: "ticket-reply",
          withFront: true,
          feeds: false,
          pages: true,
        },
        adminMenu: {
          enabled: false,
        },
      },
    ],
  },
];
