/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as accessControl from "../accessControl.js";
import type * as actions_payments from "../actions/payments.js";
import type * as auth_clerkAuth from "../auth/clerkAuth.js";
import type * as auth_mondayAuth from "../auth/mondayAuth.js";
import type * as auth_users from "../auth/users.js";
import type * as calendar_attendance_index from "../calendar/attendance/index.js";
import type * as calendar_attendance_mutations from "../calendar/attendance/mutations.js";
import type * as calendar_attendance_queries from "../calendar/attendance/queries.js";
import type * as calendar_attendees from "../calendar/attendees.js";
import type * as calendar_crud from "../calendar/crud.js";
import type * as calendar_events_crud from "../calendar/events/crud.js";
import type * as calendar_events_index from "../calendar/events/index.js";
import type * as calendar_events_mutations from "../calendar/events/mutations.js";
import type * as calendar_events_queries from "../calendar/events/queries.js";
import type * as calendar_index from "../calendar/index.js";
import type * as calendar_invitations from "../calendar/invitations.js";
import type * as calendar_lib_authUtils from "../calendar/lib/authUtils.js";
import type * as calendar_lib_dateUtils from "../calendar/lib/dateUtils.js";
import type * as calendar_lib_index from "../calendar/lib/index.js";
import type * as calendar_permissions from "../calendar/permissions.js";
import type * as calendar_queries from "../calendar/queries.js";
import type * as calendar_reminders_index from "../calendar/reminders/index.js";
import type * as calendar_reminders_mutations from "../calendar/reminders/mutations.js";
import type * as calendar_reminders_queries from "../calendar/reminders/queries.js";
import type * as calendar_reminders from "../calendar/reminders.js";
import type * as calendar_schema_calendarSchema from "../calendar/schema/calendarSchema.js";
import type * as calendar_schema_index from "../calendar/schema/index.js";
import type * as cart from "../cart.js";
import type * as cms__generated_collections_Posts from "../cms/_generated/collections/Posts.js";
import type * as cms__generated_collections_Transactions from "../cms/_generated/collections/Transactions.js";
import type * as cms__generated_collections_index from "../cms/_generated/collections/index.js";
import type * as cms__generated_index from "../cms/_generated/index.js";
import type * as cms_categories from "../cms/categories.js";
import type * as cms_contentTypes from "../cms/contentTypes.js";
import type * as cms_index from "../cms/index.js";
import type * as cms_init_builtInContentTypes from "../cms/init/builtInContentTypes.js";
import type * as cms_init_index from "../cms/init/index.js";
import type * as cms_lib_contentTypes from "../cms/lib/contentTypes.js";
import type * as cms_mutations from "../cms/mutations.js";
import type * as cms_queries from "../cms/queries.js";
import type * as cms_schema_contentTypesSchema from "../cms/schema/contentTypesSchema.js";
import type * as cms_schema_index from "../cms/schema/index.js";
import type * as cms_schema_postsSchema from "../cms/schema/postsSchema.js";
import type * as contacts_crud from "../contacts/crud.js";
import type * as contacts_import from "../contacts/import.js";
import type * as contacts_index from "../contacts/index.js";
import type * as contacts_organizations from "../contacts/organizations.js";
import type * as contacts_queries from "../contacts/queries.js";
import type * as contacts_schema_contactsSchema from "../contacts/schema/contactsSchema.js";
import type * as contacts_schema_index from "../contacts/schema/index.js";
import type * as contacts_tags from "../contacts/tags.js";
import type * as contacts_types from "../contacts/types.js";
import type * as core_lib_auth from "../core/lib/auth.js";
import type * as core_lib_index from "../core/lib/index.js";
import type * as core_lib_permissions from "../core/lib/permissions.js";
import type * as core_schema_index from "../core/schema/index.js";
import type * as core_schema_permissionsSchema from "../core/schema/permissionsSchema.js";
import type * as core_schema_postsSchema from "../core/schema/postsSchema.js";
import type * as core_schema_rolesSchema from "../core/schema/rolesSchema.js";
import type * as courses from "../courses.js";
import type * as downloads_index from "../downloads/index.js";
import type * as downloads_internal from "../downloads/internal.js";
import type * as downloads_lib_fileTypeUtils from "../downloads/lib/fileTypeUtils.js";
import type * as downloads_lib_helpers from "../downloads/lib/helpers.js";
import type * as downloads_lib_imageExtraction from "../downloads/lib/imageExtraction.js";
import type * as downloads_lib_index from "../downloads/lib/index.js";
import type * as downloads_library from "../downloads/library.js";
import type * as downloads_mutations from "../downloads/mutations.js";
import type * as downloads_queries from "../downloads/queries.js";
import type * as downloads_schema_index from "../downloads/schema/index.js";
import type * as downloads_schema_types from "../downloads/schema/types.js";
import type * as downloads from "../downloads.js";
import type * as downloadsLibrary from "../downloadsLibrary.js";
import type * as ecommerce_cart_cartUtils from "../ecommerce/cart/cartUtils.js";
import type * as ecommerce_cart_index from "../ecommerce/cart/index.js";
import type * as ecommerce_categories_index from "../ecommerce/categories/index.js";
import type * as ecommerce_checkout_customCheckouts from "../ecommerce/checkout/customCheckouts.js";
import type * as ecommerce_checkout_index from "../ecommerce/checkout/index.js";
import type * as ecommerce_index from "../ecommerce/index.js";
import type * as ecommerce_lib_index from "../ecommerce/lib/index.js";
import type * as ecommerce_lib_permissions from "../ecommerce/lib/permissions.js";
import type * as ecommerce_lib_pricing from "../ecommerce/lib/pricing.js";
import type * as ecommerce_lib_stockUtils from "../ecommerce/lib/stockUtils.js";
import type * as ecommerce_orders_index from "../ecommerce/orders/index.js";
import type * as ecommerce_payments_index from "../ecommerce/payments/index.js";
import type * as ecommerce_products_index from "../ecommerce/products/index.js";
import type * as ecommerce_products_mutations from "../ecommerce/products/mutations.js";
import type * as ecommerce_schema_cartSchema from "../ecommerce/schema/cartSchema.js";
import type * as ecommerce_schema_categoriesSchema from "../ecommerce/schema/categoriesSchema.js";
import type * as ecommerce_schema_checkoutsSchema from "../ecommerce/schema/checkoutsSchema.js";
import type * as ecommerce_schema_couponsSchema from "../ecommerce/schema/couponsSchema.js";
import type * as ecommerce_schema_index from "../ecommerce/schema/index.js";
import type * as ecommerce_schema_ordersSchema from "../ecommerce/schema/ordersSchema.js";
import type * as ecommerce_schema_paymentMethodsSchema from "../ecommerce/schema/paymentMethodsSchema.js";
import type * as ecommerce_schema_productReviewsSchema from "../ecommerce/schema/productReviewsSchema.js";
import type * as ecommerce_schema_productsSchema from "../ecommerce/schema/productsSchema.js";
import type * as ecommerce_schema_shippingMethodsSchema from "../ecommerce/schema/shippingMethodsSchema.js";
import type * as ecommerce_schema_subscriptionsSchema from "../ecommerce/schema/subscriptionsSchema.js";
import type * as ecommerce_schema_taxRatesSchema from "../ecommerce/schema/taxRatesSchema.js";
import type * as ecommerce_schema_transactionsSchema from "../ecommerce/schema/transactionsSchema.js";
import type * as ecommerce_schema_wishlistSchema from "../ecommerce/schema/wishlistSchema.js";
import type * as ecommerce_variations_index from "../ecommerce/variations/index.js";
import type * as ecommerce from "../ecommerce.js";
import type * as env from "../env.js";
import type * as groupPosts from "../groupPosts.js";
import type * as groups_index from "../groups/index.js";
import type * as groups_lib_helpers from "../groups/lib/helpers.js";
import type * as groups_lib_index from "../groups/lib/index.js";
import type * as groups_mutations from "../groups/mutations.js";
import type * as groups_posts from "../groups/posts.js";
import type * as groups_queries from "../groups/queries.js";
import type * as groups_schema_groupsSchema from "../groups/schema/groupsSchema.js";
import type * as groups_schema_index from "../groups/schema/index.js";
import type * as groups_schema_types from "../groups/schema/types.js";
import type * as groups from "../groups.js";
import type * as helpdesk from "../helpdesk.js";
import type * as http_wordpress from "../http/wordpress.js";
import type * as http from "../http.js";
import type * as integrations_index from "../integrations/index.js";
import type * as integrations_schema_index from "../integrations/schema/index.js";
import type * as integrations_test_basic from "../integrations/test/basic.js";
import type * as integrations from "../integrations.js";
import type * as integrations_old_apps_index from "../integrations_old/apps/index.js";
import type * as integrations_old_apps_management from "../integrations_old/apps/management.js";
import type * as integrations_old_apps_registration from "../integrations_old/apps/registration.js";
import type * as integrations_old_apps_test_wordpress from "../integrations_old/apps/test_wordpress.js";
import type * as integrations_old_apps_wordpress from "../integrations_old/apps/wordpress.js";
import type * as integrations_old_audit from "../integrations_old/audit.js";
import type * as integrations_old_connections_apikey from "../integrations_old/connections/apikey.js";
import type * as integrations_old_connections_basic from "../integrations_old/connections/basic.js";
import type * as integrations_old_connections_credentials from "../integrations_old/connections/credentials.js";
import type * as integrations_old_connections_index from "../integrations_old/connections/index.js";
import type * as integrations_old_connections_management from "../integrations_old/connections/management.js";
import type * as integrations_old_connections_monitoring from "../integrations_old/connections/monitoring.js";
import type * as integrations_old_connections_oauth from "../integrations_old/connections/oauth.js";
import type * as integrations_old_connections_wordpress from "../integrations_old/connections/wordpress.js";
import type * as integrations_old_index from "../integrations_old/index.js";
import type * as integrations_old_lib_audit_index from "../integrations_old/lib/audit/index.js";
import type * as integrations_old_lib_auth from "../integrations_old/lib/auth.js";
import type * as integrations_old_lib_errorHandling from "../integrations_old/lib/errorHandling.js";
import type * as integrations_old_lib_helpers from "../integrations_old/lib/helpers.js";
import type * as integrations_old_lib_index from "../integrations_old/lib/index.js";
import type * as integrations_old_lib_masking_index from "../integrations_old/lib/masking/index.js";
import type * as integrations_old_lib_permissions_index from "../integrations_old/lib/permissions/index.js";
import type * as integrations_old_lib_security_encryption from "../integrations_old/lib/security/encryption.js";
import type * as integrations_old_lib_security_index from "../integrations_old/lib/security/index.js";
import type * as integrations_old_lib_security_keyManagement from "../integrations_old/lib/security/keyManagement.js";
import type * as integrations_old_lib_security_rotation from "../integrations_old/lib/security/rotation.js";
import type * as integrations_old_lib_testing_index from "../integrations_old/lib/testing/index.js";
import type * as integrations_old_lib_testing_securityTests from "../integrations_old/lib/testing/securityTests.js";
import type * as integrations_old_lib_validators from "../integrations_old/lib/validators.js";
import type * as integrations_old_scenarios_crons from "../integrations_old/scenarios/crons.js";
import type * as integrations_old_scenarios_errorHandling from "../integrations_old/scenarios/errorHandling.js";
import type * as integrations_old_scenarios_execution from "../integrations_old/scenarios/execution.js";
import type * as integrations_old_scenarios_index from "../integrations_old/scenarios/index.js";
import type * as integrations_old_scenarios_management from "../integrations_old/scenarios/management.js";
import type * as integrations_old_scenarios_monitoring from "../integrations_old/scenarios/monitoring.js";
import type * as integrations_old_scenarios_nodes from "../integrations_old/scenarios/nodes.js";
import type * as integrations_old_scenarios_notifications from "../integrations_old/scenarios/notifications.js";
import type * as integrations_old_scenarios_performance from "../integrations_old/scenarios/performance.js";
import type * as integrations_old_scenarios_recovery from "../integrations_old/scenarios/recovery.js";
import type * as integrations_old_scenarios_retryManager from "../integrations_old/scenarios/retryManager.js";
import type * as integrations_old_scenarios_triggers from "../integrations_old/scenarios/triggers.js";
import type * as integrations_old_schema_index from "../integrations_old/schema/index.js";
import type * as integrations_old_schema_integrationsSchema from "../integrations_old/schema/integrationsSchema.js";
import type * as integrations_old_schema_test_schema from "../integrations_old/schema/test_schema.js";
import type * as integrations_old_schema_types from "../integrations_old/schema/types.js";
import type * as integrations_old_transformations_core from "../integrations_old/transformations/core.js";
import type * as integrations_old_transformations_functions_array from "../integrations_old/transformations/functions/array.js";
import type * as integrations_old_transformations_functions_custom from "../integrations_old/transformations/functions/custom.js";
import type * as integrations_old_transformations_functions_date from "../integrations_old/transformations/functions/date.js";
import type * as integrations_old_transformations_functions_json from "../integrations_old/transformations/functions/json.js";
import type * as integrations_old_transformations_functions_logic from "../integrations_old/transformations/functions/logic.js";
import type * as integrations_old_transformations_functions_number from "../integrations_old/transformations/functions/number.js";
import type * as integrations_old_transformations_functions_object from "../integrations_old/transformations/functions/object.js";
import type * as integrations_old_transformations_functions_string from "../integrations_old/transformations/functions/string.js";
import type * as integrations_old_transformations_index from "../integrations_old/transformations/index.js";
import type * as integrations_old_transformations_registry from "../integrations_old/transformations/registry.js";
import type * as integrations_old_transformations_seed from "../integrations_old/transformations/seed.js";
import type * as integrations_old_transformations_types from "../integrations_old/transformations/types.js";
import type * as integrations_old_transformations_utils from "../integrations_old/transformations/utils.js";
import type * as lib_db from "../lib/db.js";
import type * as lib_fileTypes from "../lib/fileTypes.js";
import type * as lib_permissions_hasPermission from "../lib/permissions/hasPermission.js";
import type * as lib_permissions_index from "../lib/permissions/index.js";
import type * as lib_permissions_requirePermission from "../lib/permissions/requirePermission.js";
import type * as lib_permissions_userAuth from "../lib/permissions/userAuth.js";
import type * as lib_queryAnalyzer from "../lib/queryAnalyzer.js";
import type * as lib_slugs from "../lib/slugs.js";
import type * as lms_courses_index from "../lms/courses/index.js";
import type * as lms_enrollments_index from "../lms/enrollments/index.js";
import type * as lms_index from "../lms/index.js";
import type * as lms_lib_index from "../lms/lib/index.js";
import type * as lms_schema_index from "../lms/schema/index.js";
import type * as lms_schema_lmsSchema from "../lms/schema/lmsSchema.js";
import type * as lms_topics_index from "../lms/topics/index.js";
import type * as monday_actions from "../monday/actions.js";
import type * as monday_client from "../monday/client.js";
import type * as monday_crons from "../monday/crons.js";
import type * as monday_index from "../monday/index.js";
import type * as monday_internal from "../monday/internal.js";
import type * as monday_lib_api from "../monday/lib/api.js";
import type * as monday_lib_conflicts from "../monday/lib/conflicts.js";
import type * as monday_lib_index from "../monday/lib/index.js";
import type * as monday_lib_logging from "../monday/lib/logging.js";
import type * as monday_lib_optimizedApi from "../monday/lib/optimizedApi.js";
import type * as monday_lib_orderSync from "../monday/lib/orderSync.js";
import type * as monday_lib_performance from "../monday/lib/performance.js";
import type * as monday_lib_rules from "../monday/lib/rules.js";
import type * as monday_lib_sync from "../monday/lib/sync.js";
import type * as monday_lib_types from "../monday/lib/types.js";
import type * as monday_mutations from "../monday/mutations.js";
import type * as monday_queries from "../monday/queries.js";
import type * as notifications_index from "../notifications/index.js";
import type * as notifications_lib_feedNotifications from "../notifications/lib/feedNotifications.js";
import type * as notifications_lib_formatters from "../notifications/lib/formatters.js";
import type * as notifications_lib_index from "../notifications/lib/index.js";
import type * as notifications_lib_preferences from "../notifications/lib/preferences.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_preferences from "../notifications/preferences.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as notifications_schema_index from "../notifications/schema/index.js";
import type * as notifications_schema_notificationsSchema from "../notifications/schema/notificationsSchema.js";
import type * as notifications_schema_types from "../notifications/schema/types.js";
import type * as orders from "../orders.js";
import type * as permissionsUtils from "../permissionsUtils.js";
import type * as posts from "../posts.js";
import type * as roles from "../roles.js";
import type * as rules_api from "../rules/api.js";
import type * as rules_execution from "../rules/execution.js";
import type * as rules_integrations from "../rules/integrations.js";
import type * as rules_lib_engine from "../rules/lib/engine.js";
import type * as rules_lib_index from "../rules/lib/index.js";
import type * as rules_lib_integration_adapters_monday_actions from "../rules/lib/integration/adapters/monday/actions.js";
import type * as rules_lib_integration_adapters_monday_conditions from "../rules/lib/integration/adapters/monday/conditions.js";
import type * as rules_lib_integration_adapters_monday_index from "../rules/lib/integration/adapters/monday/index.js";
import type * as rules_lib_integration_adapters_monday_triggers from "../rules/lib/integration/adapters/monday/triggers.js";
import type * as rules_lib_integration_adapters_monday from "../rules/lib/integration/adapters/monday.js";
import type * as rules_lib_integration_adapters_mondayContextFactory from "../rules/lib/integration/adapters/mondayContextFactory.js";
import type * as rules_lib_integration_adapters_wordpress_actions from "../rules/lib/integration/adapters/wordpress/actions.js";
import type * as rules_lib_integration_adapters_wordpress_conditions from "../rules/lib/integration/adapters/wordpress/conditions.js";
import type * as rules_lib_integration_adapters_wordpress_triggers from "../rules/lib/integration/adapters/wordpress/triggers.js";
import type * as rules_lib_integration_adapters_wordpress from "../rules/lib/integration/adapters/wordpress.js";
import type * as rules_lib_integration_adapters_wordpressContextFactory from "../rules/lib/integration/adapters/wordpressContextFactory.js";
import type * as rules_lib_integration_config from "../rules/lib/integration/config.js";
import type * as rules_lib_integration_index from "../rules/lib/integration/index.js";
import type * as rules_lib_integration_plugin from "../rules/lib/integration/plugin.js";
import type * as rules_lib_integration_plugins from "../rules/lib/integration/plugins.js";
import type * as rules_lib_integration_registry from "../rules/lib/integration/registry.js";
import type * as rules_lib_interfaces from "../rules/lib/interfaces.js";
import type * as rules_lib_logger from "../rules/lib/logger.js";
import type * as rules_lib_migration from "../rules/lib/migration.js";
import type * as rules_lib_registry from "../rules/lib/registry.js";
import type * as rules_lib_utils from "../rules/lib/utils.js";
import type * as rules_migration from "../rules/migration.js";
import type * as rules_register_monday from "../rules/register_monday.js";
import type * as rules_register_wordpress from "../rules/register_wordpress.js";
import type * as rules_schema_index from "../rules/schema/index.js";
import type * as rules_schema_rules from "../rules/schema/rules.js";
import type * as search from "../search.js";
import type * as seedPermissions from "../seedPermissions.js";
import type * as shared_auth from "../shared/auth.js";
import type * as shared_constants from "../shared/constants.js";
import type * as shared_dates from "../shared/dates.js";
import type * as shared_errors from "../shared/errors.js";
import type * as shared_formatting from "../shared/formatting.js";
import type * as shared_index from "../shared/index.js";
import type * as shared_pagination from "../shared/pagination.js";
import type * as shared_search from "../shared/search.js";
import type * as shared_validation from "../shared/validation.js";
import type * as shared_validators from "../shared/validators.js";
import type * as socialfeed_crons from "../socialfeed/crons.js";
import type * as socialfeed_lib_recommendationEngine from "../socialfeed/lib/recommendationEngine.js";
import type * as socialfeed_lib_trendingAlgorithm from "../socialfeed/lib/trendingAlgorithm.js";
import type * as socialfeed_mutations from "../socialfeed/mutations.js";
import type * as socialfeed_queries from "../socialfeed/queries.js";
import type * as socialfeed_schema_commentsSchema from "../socialfeed/schema/commentsSchema.js";
import type * as socialfeed_schema_contentRecommendationsSchema from "../socialfeed/schema/contentRecommendationsSchema.js";
import type * as socialfeed_schema_feedItemsSchema from "../socialfeed/schema/feedItemsSchema.js";
import type * as socialfeed_schema_hashtagsSchema from "../socialfeed/schema/hashtagsSchema.js";
import type * as socialfeed_schema_index from "../socialfeed/schema/index.js";
import type * as socialfeed_schema_reactionsSchema from "../socialfeed/schema/reactionsSchema.js";
import type * as socialfeed_schema_savedItemsSchema from "../socialfeed/schema/savedItemsSchema.js";
import type * as socialfeed_schema_subscriptionsSchema from "../socialfeed/schema/subscriptionsSchema.js";
import type * as socialfeed_schema_topicFollowsSchema from "../socialfeed/schema/topicFollowsSchema.js";
import type * as socialfeed_schema_trendingContentSchema from "../socialfeed/schema/trendingContentSchema.js";
import type * as test_schema from "../test_schema.js";
import type * as topics from "../topics.js";
import type * as users_index from "../users/index.js";
import type * as users_lib_index from "../users/lib/index.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as users_schema_index from "../users/schema/index.js";
import type * as users_schema_types from "../users/schema/types.js";
import type * as users_schema_usersSchema from "../users/schema/usersSchema.js";
import type * as users from "../users.js";
import type * as versionControl from "../versionControl.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  accessControl: typeof accessControl;
  "actions/payments": typeof actions_payments;
  "auth/clerkAuth": typeof auth_clerkAuth;
  "auth/mondayAuth": typeof auth_mondayAuth;
  "auth/users": typeof auth_users;
  "calendar/attendance/index": typeof calendar_attendance_index;
  "calendar/attendance/mutations": typeof calendar_attendance_mutations;
  "calendar/attendance/queries": typeof calendar_attendance_queries;
  "calendar/attendees": typeof calendar_attendees;
  "calendar/crud": typeof calendar_crud;
  "calendar/events/crud": typeof calendar_events_crud;
  "calendar/events/index": typeof calendar_events_index;
  "calendar/events/mutations": typeof calendar_events_mutations;
  "calendar/events/queries": typeof calendar_events_queries;
  "calendar/index": typeof calendar_index;
  "calendar/invitations": typeof calendar_invitations;
  "calendar/lib/authUtils": typeof calendar_lib_authUtils;
  "calendar/lib/dateUtils": typeof calendar_lib_dateUtils;
  "calendar/lib/index": typeof calendar_lib_index;
  "calendar/permissions": typeof calendar_permissions;
  "calendar/queries": typeof calendar_queries;
  "calendar/reminders/index": typeof calendar_reminders_index;
  "calendar/reminders/mutations": typeof calendar_reminders_mutations;
  "calendar/reminders/queries": typeof calendar_reminders_queries;
  "calendar/reminders": typeof calendar_reminders;
  "calendar/schema/calendarSchema": typeof calendar_schema_calendarSchema;
  "calendar/schema/index": typeof calendar_schema_index;
  cart: typeof cart;
  "cms/_generated/collections/Posts": typeof cms__generated_collections_Posts;
  "cms/_generated/collections/Transactions": typeof cms__generated_collections_Transactions;
  "cms/_generated/collections/index": typeof cms__generated_collections_index;
  "cms/_generated/index": typeof cms__generated_index;
  "cms/categories": typeof cms_categories;
  "cms/contentTypes": typeof cms_contentTypes;
  "cms/index": typeof cms_index;
  "cms/init/builtInContentTypes": typeof cms_init_builtInContentTypes;
  "cms/init/index": typeof cms_init_index;
  "cms/lib/contentTypes": typeof cms_lib_contentTypes;
  "cms/mutations": typeof cms_mutations;
  "cms/queries": typeof cms_queries;
  "cms/schema/contentTypesSchema": typeof cms_schema_contentTypesSchema;
  "cms/schema/index": typeof cms_schema_index;
  "cms/schema/postsSchema": typeof cms_schema_postsSchema;
  "contacts/crud": typeof contacts_crud;
  "contacts/import": typeof contacts_import;
  "contacts/index": typeof contacts_index;
  "contacts/organizations": typeof contacts_organizations;
  "contacts/queries": typeof contacts_queries;
  "contacts/schema/contactsSchema": typeof contacts_schema_contactsSchema;
  "contacts/schema/index": typeof contacts_schema_index;
  "contacts/tags": typeof contacts_tags;
  "contacts/types": typeof contacts_types;
  "core/lib/auth": typeof core_lib_auth;
  "core/lib/index": typeof core_lib_index;
  "core/lib/permissions": typeof core_lib_permissions;
  "core/schema/index": typeof core_schema_index;
  "core/schema/permissionsSchema": typeof core_schema_permissionsSchema;
  "core/schema/postsSchema": typeof core_schema_postsSchema;
  "core/schema/rolesSchema": typeof core_schema_rolesSchema;
  courses: typeof courses;
  "downloads/index": typeof downloads_index;
  "downloads/internal": typeof downloads_internal;
  "downloads/lib/fileTypeUtils": typeof downloads_lib_fileTypeUtils;
  "downloads/lib/helpers": typeof downloads_lib_helpers;
  "downloads/lib/imageExtraction": typeof downloads_lib_imageExtraction;
  "downloads/lib/index": typeof downloads_lib_index;
  "downloads/library": typeof downloads_library;
  "downloads/mutations": typeof downloads_mutations;
  "downloads/queries": typeof downloads_queries;
  "downloads/schema/index": typeof downloads_schema_index;
  "downloads/schema/types": typeof downloads_schema_types;
  downloads: typeof downloads;
  downloadsLibrary: typeof downloadsLibrary;
  "ecommerce/cart/cartUtils": typeof ecommerce_cart_cartUtils;
  "ecommerce/cart/index": typeof ecommerce_cart_index;
  "ecommerce/categories/index": typeof ecommerce_categories_index;
  "ecommerce/checkout/customCheckouts": typeof ecommerce_checkout_customCheckouts;
  "ecommerce/checkout/index": typeof ecommerce_checkout_index;
  "ecommerce/index": typeof ecommerce_index;
  "ecommerce/lib/index": typeof ecommerce_lib_index;
  "ecommerce/lib/permissions": typeof ecommerce_lib_permissions;
  "ecommerce/lib/pricing": typeof ecommerce_lib_pricing;
  "ecommerce/lib/stockUtils": typeof ecommerce_lib_stockUtils;
  "ecommerce/orders/index": typeof ecommerce_orders_index;
  "ecommerce/payments/index": typeof ecommerce_payments_index;
  "ecommerce/products/index": typeof ecommerce_products_index;
  "ecommerce/products/mutations": typeof ecommerce_products_mutations;
  "ecommerce/schema/cartSchema": typeof ecommerce_schema_cartSchema;
  "ecommerce/schema/categoriesSchema": typeof ecommerce_schema_categoriesSchema;
  "ecommerce/schema/checkoutsSchema": typeof ecommerce_schema_checkoutsSchema;
  "ecommerce/schema/couponsSchema": typeof ecommerce_schema_couponsSchema;
  "ecommerce/schema/index": typeof ecommerce_schema_index;
  "ecommerce/schema/ordersSchema": typeof ecommerce_schema_ordersSchema;
  "ecommerce/schema/paymentMethodsSchema": typeof ecommerce_schema_paymentMethodsSchema;
  "ecommerce/schema/productReviewsSchema": typeof ecommerce_schema_productReviewsSchema;
  "ecommerce/schema/productsSchema": typeof ecommerce_schema_productsSchema;
  "ecommerce/schema/shippingMethodsSchema": typeof ecommerce_schema_shippingMethodsSchema;
  "ecommerce/schema/subscriptionsSchema": typeof ecommerce_schema_subscriptionsSchema;
  "ecommerce/schema/taxRatesSchema": typeof ecommerce_schema_taxRatesSchema;
  "ecommerce/schema/transactionsSchema": typeof ecommerce_schema_transactionsSchema;
  "ecommerce/schema/wishlistSchema": typeof ecommerce_schema_wishlistSchema;
  "ecommerce/variations/index": typeof ecommerce_variations_index;
  ecommerce: typeof ecommerce;
  env: typeof env;
  groupPosts: typeof groupPosts;
  "groups/index": typeof groups_index;
  "groups/lib/helpers": typeof groups_lib_helpers;
  "groups/lib/index": typeof groups_lib_index;
  "groups/mutations": typeof groups_mutations;
  "groups/posts": typeof groups_posts;
  "groups/queries": typeof groups_queries;
  "groups/schema/groupsSchema": typeof groups_schema_groupsSchema;
  "groups/schema/index": typeof groups_schema_index;
  "groups/schema/types": typeof groups_schema_types;
  groups: typeof groups;
  helpdesk: typeof helpdesk;
  "http/wordpress": typeof http_wordpress;
  http: typeof http;
  "integrations/index": typeof integrations_index;
  "integrations/schema/index": typeof integrations_schema_index;
  "integrations/test/basic": typeof integrations_test_basic;
  integrations: typeof integrations;
  "integrations_old/apps/index": typeof integrations_old_apps_index;
  "integrations_old/apps/management": typeof integrations_old_apps_management;
  "integrations_old/apps/registration": typeof integrations_old_apps_registration;
  "integrations_old/apps/test_wordpress": typeof integrations_old_apps_test_wordpress;
  "integrations_old/apps/wordpress": typeof integrations_old_apps_wordpress;
  "integrations_old/audit": typeof integrations_old_audit;
  "integrations_old/connections/apikey": typeof integrations_old_connections_apikey;
  "integrations_old/connections/basic": typeof integrations_old_connections_basic;
  "integrations_old/connections/credentials": typeof integrations_old_connections_credentials;
  "integrations_old/connections/index": typeof integrations_old_connections_index;
  "integrations_old/connections/management": typeof integrations_old_connections_management;
  "integrations_old/connections/monitoring": typeof integrations_old_connections_monitoring;
  "integrations_old/connections/oauth": typeof integrations_old_connections_oauth;
  "integrations_old/connections/wordpress": typeof integrations_old_connections_wordpress;
  "integrations_old/index": typeof integrations_old_index;
  "integrations_old/lib/audit/index": typeof integrations_old_lib_audit_index;
  "integrations_old/lib/auth": typeof integrations_old_lib_auth;
  "integrations_old/lib/errorHandling": typeof integrations_old_lib_errorHandling;
  "integrations_old/lib/helpers": typeof integrations_old_lib_helpers;
  "integrations_old/lib/index": typeof integrations_old_lib_index;
  "integrations_old/lib/masking/index": typeof integrations_old_lib_masking_index;
  "integrations_old/lib/permissions/index": typeof integrations_old_lib_permissions_index;
  "integrations_old/lib/security/encryption": typeof integrations_old_lib_security_encryption;
  "integrations_old/lib/security/index": typeof integrations_old_lib_security_index;
  "integrations_old/lib/security/keyManagement": typeof integrations_old_lib_security_keyManagement;
  "integrations_old/lib/security/rotation": typeof integrations_old_lib_security_rotation;
  "integrations_old/lib/testing/index": typeof integrations_old_lib_testing_index;
  "integrations_old/lib/testing/securityTests": typeof integrations_old_lib_testing_securityTests;
  "integrations_old/lib/validators": typeof integrations_old_lib_validators;
  "integrations_old/scenarios/crons": typeof integrations_old_scenarios_crons;
  "integrations_old/scenarios/errorHandling": typeof integrations_old_scenarios_errorHandling;
  "integrations_old/scenarios/execution": typeof integrations_old_scenarios_execution;
  "integrations_old/scenarios/index": typeof integrations_old_scenarios_index;
  "integrations_old/scenarios/management": typeof integrations_old_scenarios_management;
  "integrations_old/scenarios/monitoring": typeof integrations_old_scenarios_monitoring;
  "integrations_old/scenarios/nodes": typeof integrations_old_scenarios_nodes;
  "integrations_old/scenarios/notifications": typeof integrations_old_scenarios_notifications;
  "integrations_old/scenarios/performance": typeof integrations_old_scenarios_performance;
  "integrations_old/scenarios/recovery": typeof integrations_old_scenarios_recovery;
  "integrations_old/scenarios/retryManager": typeof integrations_old_scenarios_retryManager;
  "integrations_old/scenarios/triggers": typeof integrations_old_scenarios_triggers;
  "integrations_old/schema/index": typeof integrations_old_schema_index;
  "integrations_old/schema/integrationsSchema": typeof integrations_old_schema_integrationsSchema;
  "integrations_old/schema/test_schema": typeof integrations_old_schema_test_schema;
  "integrations_old/schema/types": typeof integrations_old_schema_types;
  "integrations_old/transformations/core": typeof integrations_old_transformations_core;
  "integrations_old/transformations/functions/array": typeof integrations_old_transformations_functions_array;
  "integrations_old/transformations/functions/custom": typeof integrations_old_transformations_functions_custom;
  "integrations_old/transformations/functions/date": typeof integrations_old_transformations_functions_date;
  "integrations_old/transformations/functions/json": typeof integrations_old_transformations_functions_json;
  "integrations_old/transformations/functions/logic": typeof integrations_old_transformations_functions_logic;
  "integrations_old/transformations/functions/number": typeof integrations_old_transformations_functions_number;
  "integrations_old/transformations/functions/object": typeof integrations_old_transformations_functions_object;
  "integrations_old/transformations/functions/string": typeof integrations_old_transformations_functions_string;
  "integrations_old/transformations/index": typeof integrations_old_transformations_index;
  "integrations_old/transformations/registry": typeof integrations_old_transformations_registry;
  "integrations_old/transformations/seed": typeof integrations_old_transformations_seed;
  "integrations_old/transformations/types": typeof integrations_old_transformations_types;
  "integrations_old/transformations/utils": typeof integrations_old_transformations_utils;
  "lib/db": typeof lib_db;
  "lib/fileTypes": typeof lib_fileTypes;
  "lib/permissions/hasPermission": typeof lib_permissions_hasPermission;
  "lib/permissions/index": typeof lib_permissions_index;
  "lib/permissions/requirePermission": typeof lib_permissions_requirePermission;
  "lib/permissions/userAuth": typeof lib_permissions_userAuth;
  "lib/queryAnalyzer": typeof lib_queryAnalyzer;
  "lib/slugs": typeof lib_slugs;
  "lms/courses/index": typeof lms_courses_index;
  "lms/enrollments/index": typeof lms_enrollments_index;
  "lms/index": typeof lms_index;
  "lms/lib/index": typeof lms_lib_index;
  "lms/schema/index": typeof lms_schema_index;
  "lms/schema/lmsSchema": typeof lms_schema_lmsSchema;
  "lms/topics/index": typeof lms_topics_index;
  "monday/actions": typeof monday_actions;
  "monday/client": typeof monday_client;
  "monday/crons": typeof monday_crons;
  "monday/index": typeof monday_index;
  "monday/internal": typeof monday_internal;
  "monday/lib/api": typeof monday_lib_api;
  "monday/lib/conflicts": typeof monday_lib_conflicts;
  "monday/lib/index": typeof monday_lib_index;
  "monday/lib/logging": typeof monday_lib_logging;
  "monday/lib/optimizedApi": typeof monday_lib_optimizedApi;
  "monday/lib/orderSync": typeof monday_lib_orderSync;
  "monday/lib/performance": typeof monday_lib_performance;
  "monday/lib/rules": typeof monday_lib_rules;
  "monday/lib/sync": typeof monday_lib_sync;
  "monday/lib/types": typeof monday_lib_types;
  "monday/mutations": typeof monday_mutations;
  "monday/queries": typeof monday_queries;
  "notifications/index": typeof notifications_index;
  "notifications/lib/feedNotifications": typeof notifications_lib_feedNotifications;
  "notifications/lib/formatters": typeof notifications_lib_formatters;
  "notifications/lib/index": typeof notifications_lib_index;
  "notifications/lib/preferences": typeof notifications_lib_preferences;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/preferences": typeof notifications_preferences;
  "notifications/queries": typeof notifications_queries;
  "notifications/schema/index": typeof notifications_schema_index;
  "notifications/schema/notificationsSchema": typeof notifications_schema_notificationsSchema;
  "notifications/schema/types": typeof notifications_schema_types;
  orders: typeof orders;
  permissionsUtils: typeof permissionsUtils;
  posts: typeof posts;
  roles: typeof roles;
  "rules/api": typeof rules_api;
  "rules/execution": typeof rules_execution;
  "rules/integrations": typeof rules_integrations;
  "rules/lib/engine": typeof rules_lib_engine;
  "rules/lib/index": typeof rules_lib_index;
  "rules/lib/integration/adapters/monday/actions": typeof rules_lib_integration_adapters_monday_actions;
  "rules/lib/integration/adapters/monday/conditions": typeof rules_lib_integration_adapters_monday_conditions;
  "rules/lib/integration/adapters/monday/index": typeof rules_lib_integration_adapters_monday_index;
  "rules/lib/integration/adapters/monday/triggers": typeof rules_lib_integration_adapters_monday_triggers;
  "rules/lib/integration/adapters/monday": typeof rules_lib_integration_adapters_monday;
  "rules/lib/integration/adapters/mondayContextFactory": typeof rules_lib_integration_adapters_mondayContextFactory;
  "rules/lib/integration/adapters/wordpress/actions": typeof rules_lib_integration_adapters_wordpress_actions;
  "rules/lib/integration/adapters/wordpress/conditions": typeof rules_lib_integration_adapters_wordpress_conditions;
  "rules/lib/integration/adapters/wordpress/triggers": typeof rules_lib_integration_adapters_wordpress_triggers;
  "rules/lib/integration/adapters/wordpress": typeof rules_lib_integration_adapters_wordpress;
  "rules/lib/integration/adapters/wordpressContextFactory": typeof rules_lib_integration_adapters_wordpressContextFactory;
  "rules/lib/integration/config": typeof rules_lib_integration_config;
  "rules/lib/integration/index": typeof rules_lib_integration_index;
  "rules/lib/integration/plugin": typeof rules_lib_integration_plugin;
  "rules/lib/integration/plugins": typeof rules_lib_integration_plugins;
  "rules/lib/integration/registry": typeof rules_lib_integration_registry;
  "rules/lib/interfaces": typeof rules_lib_interfaces;
  "rules/lib/logger": typeof rules_lib_logger;
  "rules/lib/migration": typeof rules_lib_migration;
  "rules/lib/registry": typeof rules_lib_registry;
  "rules/lib/utils": typeof rules_lib_utils;
  "rules/migration": typeof rules_migration;
  "rules/register_monday": typeof rules_register_monday;
  "rules/register_wordpress": typeof rules_register_wordpress;
  "rules/schema/index": typeof rules_schema_index;
  "rules/schema/rules": typeof rules_schema_rules;
  search: typeof search;
  seedPermissions: typeof seedPermissions;
  "shared/auth": typeof shared_auth;
  "shared/constants": typeof shared_constants;
  "shared/dates": typeof shared_dates;
  "shared/errors": typeof shared_errors;
  "shared/formatting": typeof shared_formatting;
  "shared/index": typeof shared_index;
  "shared/pagination": typeof shared_pagination;
  "shared/search": typeof shared_search;
  "shared/validation": typeof shared_validation;
  "shared/validators": typeof shared_validators;
  "socialfeed/crons": typeof socialfeed_crons;
  "socialfeed/lib/recommendationEngine": typeof socialfeed_lib_recommendationEngine;
  "socialfeed/lib/trendingAlgorithm": typeof socialfeed_lib_trendingAlgorithm;
  "socialfeed/mutations": typeof socialfeed_mutations;
  "socialfeed/queries": typeof socialfeed_queries;
  "socialfeed/schema/commentsSchema": typeof socialfeed_schema_commentsSchema;
  "socialfeed/schema/contentRecommendationsSchema": typeof socialfeed_schema_contentRecommendationsSchema;
  "socialfeed/schema/feedItemsSchema": typeof socialfeed_schema_feedItemsSchema;
  "socialfeed/schema/hashtagsSchema": typeof socialfeed_schema_hashtagsSchema;
  "socialfeed/schema/index": typeof socialfeed_schema_index;
  "socialfeed/schema/reactionsSchema": typeof socialfeed_schema_reactionsSchema;
  "socialfeed/schema/savedItemsSchema": typeof socialfeed_schema_savedItemsSchema;
  "socialfeed/schema/subscriptionsSchema": typeof socialfeed_schema_subscriptionsSchema;
  "socialfeed/schema/topicFollowsSchema": typeof socialfeed_schema_topicFollowsSchema;
  "socialfeed/schema/trendingContentSchema": typeof socialfeed_schema_trendingContentSchema;
  test_schema: typeof test_schema;
  topics: typeof topics;
  "users/index": typeof users_index;
  "users/lib/index": typeof users_lib_index;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "users/schema/index": typeof users_schema_index;
  "users/schema/types": typeof users_schema_types;
  "users/schema/usersSchema": typeof users_schema_usersSchema;
  users: typeof users;
  versionControl: typeof versionControl;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
