// Generated by convex-payload-plugin (Collections Index)

import { Posts } from "./Posts";
import { Transactions } from "./Transactions";

export const getConvexCollections = (): any[] => {
  return [Transactions, Posts];
};
